### ISSUE TITLE
Custom JsonConverter not used

### ISSUE THREAD

**Issue by Petteroe** [Cratis/Chronicle#1466]
I am trying out Cratis Chronicle in an Asp.Net setting. I use a custom type (https://github.com/Boom-PP/Boom.Packages/tree/main/Boom.IdType) for some of my IDs. This type is annotated with a JsonConverter attribute, but that seems to not be picked up by Cratis serializers, and I cannot see any way of registering the converter on the serializer options used by Cratis. 

The symptom:
I am creating an event using this Id type as the type of one of the properties on the event. The value is empty when I look at the event in Workbench and also when it is picked up by my reactor.

Expected outcome:
I would expect that the JsonConverter attribute would be respected, or at least have a way to manually register my converter. The event using this type should have the value follow into the event store, and also back into reactors, reducers etc.

**Comment by einari** [comment]
Thanks for the detailed description and link to the type you're using. 

We're investigating why the converter is ignored.

**Comment by einari** [comment]
Also, we've been meaning to expose the ability to configure custom Json converters. Added an issue for that as well: #1469

**Comment by einari** [comment]
I did some testing and it looks like the `JsonConverter` is kicking in, but the target type in the JsonSchema becomes `Object` and since the `JsonConverter` converts it to `string`, the data in the property does not match. 

From my testing, I can see that adding the `[JsonSchemaType(typeof(string))]` attribute on the `Id` type, it gets interpreted correctly. This attribute comes from **NJsonSchema**. We are looking at replacing **NJsonSchema** for the native schema generation that comes with .NET 9. But don't have a timeframe for that right now (#1459). 

```csharp
[JsonConverter(typeof(IdConverter))]
[JsonSchemaType(typeof(string))]
public sealed record Id
{
  // ...
}
```

This looks similar to what our support for what we call a [concept](https://github.com/Cratis/Fundamentals/blob/main/Documentation/concepts.md). We have special recognition for this type of construct and change the underlying type accordingly. 

Consider the suggestion above as a workaround, as we are looking at remedying it with #1470. 
When we get to #1459 and if we conclude it is good enough for our needs, we will do a major bump in version to communicate this change.

**Comment by einari** [comment]
Please let us know if this workaround works for you and if we can close this issue in favor of the other issues registered.

**Comment by boom-morten** [comment]
I had a look at your ConceptAs thing, and prefer not to go down that route. However, the JsonSchemaType works fine as a workaround. Thank you! :)

**Comment by einari** [comment]
Great. Then I'm closing this, and we will make this a feature and more obvious in the future.
