### ISSUE TITLE
JobStep PerformWork sends message to itself to ReportStatusChange

### ISSUE THREAD

**Issue by woksin** [Cratis/Chronicle#1592]
I'm not sure if it should be as it was: `await ThisJobStep.ReportStatusChange(JobStepStatus.Running);` or if it should just call the internal `WriteStatusChange` method that does not go through the grain messaging system

**Comment by einari** [comment]
The reason it is calling `ThisJobStep.ReportStatusChange()` is that it sits in the `PerformWork()` method that is running in a different task context as part of the `CpuBoundWorker` thing. I'm not sure calling `WriteStateAsync()` would be safe, and probably not **Grain safe** for ordering. 

If it is safe however, we could basically call `this.ReportStatusChange()` instead, since we want to capture the status change. But I have a sneaky suspicion that it is not safe (based on vague memories of this)
